WIDTH = 1000
HEIGHT = 1000
MAX_CREATURES = 500
MAX_FOOD = 200
INITIAL_CREATURES = 25
INITIAL_FOOD = 100
FOOD_SPAWN_RATE = 0.2
MUTATION_RATE = 0.2
MUTATION_STRENGTH = 0.2

GRID_CELL_SIZE = 100
GRID_WIDTH = (WIDTH + GRID_CELL_SIZE - 1) // GRID_CELL_SIZE
GRID_HEIGHT = (HEIGHT + GRID_CELL_SIZE - 1) // GRID_CELL_SIZE
MAX_ITEMS_PER_CELL = 50
